version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-parking
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: parking_control_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mochil@Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
